<label for="cust-firstname">First name</label>
<input id="cust-firstname">
<label for="cust-lastname">Last name</label>
<input id="cust-lastname">
<label for="cust-password">Password</label>
<input id="cust-password">
<label for="cust-email">Email</label>
<input id="cust-email">
<label for="cust-company">Company</label>
<input id="cust-company">
<label for="cust-address">Address</label>
<input id="cust-address">
<label for="cust-city">City</label>
<input id="cust-city">
<label for="cust-state">State</label>
<input id="cust-state">
<label for="cust-country">Country</label>
<input id="cust-country">
<label for="cust-postal">Postal Code</label>
<input id="cust-postal">
<label for="cust-phone">Phone</label>
<input id="cust-phone">
<label for="cust-fax">Fax</label>
<input id="cust-fax">
<button id="btn-signup">Submit</button>